twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Kafka
    - Spring Boot
    - Elasticsearch
    - AWS
  welcome-message: "Welcome to the Twitter to Kafka Service"
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000